# Generated by Django 2.0.5 on 2018-05-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_bookmark_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='creation_date',
            field=models.DateTimeField(editable=False, verbose_name='date created'),
        ),
    ]
