# Generated by Django 2.0.5 on 2018-05-08 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0004_bookmark_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='creation_date',
            new_name='created',
        ),
    ]
