# Generated by Django 2.0.5 on 2018-05-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0005_auto_20180508_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
