# Generated by Django 2.0.5 on 2018-05-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='api_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
